version: '3.8'
 
services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: always
 
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27019/todo
      - PORT=5000
    depends_on:
      - mongo
    restart: always
 
  mongo:
    image: mongo:latest
    ports:
      - "27019:27019"
    volumes:
      - todo-db-data:/data/db
    restart: always
 
volumes:
  todo-db-data: